/**
 * Copyright (c) 2014-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @Generated by gentest/gentest.rb from gentest/fixtures/BNDYGAlignContentTest.html

#include <gtest/gtest.h>
#include <bindyoga/BindYoga.h>

TEST(YogaTest, align_content_flex_start) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root, 130);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeStyleSetHeight(root_child0, 10);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeStyleSetHeight(root_child1, 10);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 50);
  BNDYGNodeStyleSetHeight(root_child2, 10);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child3, 50);
  BNDYGNodeStyleSetHeight(root_child3, 10);
  BNDYGNodeInsertChild(root, root_child3, 3);

  const BNDYGNodeRef root_child4 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child4, 50);
  BNDYGNodeStyleSetHeight(root_child4, 10);
  BNDYGNodeInsertChild(root, root_child4, 4);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(130, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(130, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_content_flex_start_without_height_on_children) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root, 100);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeStyleSetHeight(root_child1, 10);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 50);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child3, 50);
  BNDYGNodeStyleSetHeight(root_child3, 10);
  BNDYGNodeInsertChild(root, root_child3, 3);

  const BNDYGNodeRef root_child4 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child4, 50);
  BNDYGNodeInsertChild(root, root_child4, 4);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_content_flex_start_with_flex) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root, 100);
  BNDYGNodeStyleSetHeight(root, 120);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexGrow(root_child0, 1);
  BNDYGNodeStyleSetFlexBasisPercent(root_child0, 0);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexGrow(root_child1, 1);
  BNDYGNodeStyleSetFlexBasisPercent(root_child1, 0);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeStyleSetHeight(root_child1, 10);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 50);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexGrow(root_child3, 1);
  BNDYGNodeStyleSetFlexShrink(root_child3, 1);
  BNDYGNodeStyleSetFlexBasisPercent(root_child3, 0);
  BNDYGNodeStyleSetWidth(root_child3, 50);
  BNDYGNodeInsertChild(root, root_child3, 3);

  const BNDYGNodeRef root_child4 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child4, 50);
  BNDYGNodeInsertChild(root, root_child4, 4);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(120, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(120, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(120, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(120, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_content_flex_end) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetAlignContent(root, BNDYGAlignFlexEnd);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root, 100);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeStyleSetHeight(root_child0, 10);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeStyleSetHeight(root_child1, 10);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 50);
  BNDYGNodeStyleSetHeight(root_child2, 10);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child3, 50);
  BNDYGNodeStyleSetHeight(root_child3, 10);
  BNDYGNodeInsertChild(root, root_child3, 3);

  const BNDYGNodeRef root_child4 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child4, 50);
  BNDYGNodeStyleSetHeight(root_child4, 10);
  BNDYGNodeInsertChild(root, root_child4, 4);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_content_stretch) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetAlignContent(root, BNDYGAlignStretch);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root, 150);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 50);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child3, 50);
  BNDYGNodeInsertChild(root, root_child3, 3);

  const BNDYGNodeRef root_child4 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child4, 50);
  BNDYGNodeInsertChild(root, root_child4, 4);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_content_spacebetween) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignContent(root, BNDYGAlignSpaceBetween);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root, 130);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeStyleSetHeight(root_child0, 10);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeStyleSetHeight(root_child1, 10);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 50);
  BNDYGNodeStyleSetHeight(root_child2, 10);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child3, 50);
  BNDYGNodeStyleSetHeight(root_child3, 10);
  BNDYGNodeInsertChild(root, root_child3, 3);

  const BNDYGNodeRef root_child4 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child4, 50);
  BNDYGNodeStyleSetHeight(root_child4, 10);
  BNDYGNodeInsertChild(root, root_child4, 4);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(130, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(45, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(45, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(90, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(130, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(45, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(45, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(90, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_content_spacearound) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignContent(root, BNDYGAlignSpaceAround);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root, 140);
  BNDYGNodeStyleSetHeight(root, 120);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeStyleSetHeight(root_child0, 10);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeStyleSetHeight(root_child1, 10);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 50);
  BNDYGNodeStyleSetHeight(root_child2, 10);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child3, 50);
  BNDYGNodeStyleSetHeight(root_child3, 10);
  BNDYGNodeInsertChild(root, root_child3, 3);

  const BNDYGNodeRef root_child4 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child4, 50);
  BNDYGNodeStyleSetHeight(root_child4, 10);
  BNDYGNodeInsertChild(root, root_child4, 4);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(140, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(120, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(15, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(15, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(55, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(55, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(95, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(140, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(120, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(90, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(15, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(15, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(90, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(55, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(55, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(90, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(95, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_content_stretch_row) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignContent(root, BNDYGAlignStretch);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root, 150);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 50);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child3, 50);
  BNDYGNodeInsertChild(root, root_child3, 3);

  const BNDYGNodeRef root_child4 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child4, 50);
  BNDYGNodeInsertChild(root, root_child4, 4);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_content_stretch_row_with_children) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignContent(root, BNDYGAlignStretch);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root, 150);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child0_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexGrow(root_child0_child0, 1);
  BNDYGNodeStyleSetFlexShrink(root_child0_child0, 1);
  BNDYGNodeStyleSetFlexBasisPercent(root_child0_child0, 0);
  BNDYGNodeInsertChild(root_child0, root_child0_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 50);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child3, 50);
  BNDYGNodeInsertChild(root, root_child3, 3);

  const BNDYGNodeRef root_child4 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child4, 50);
  BNDYGNodeInsertChild(root, root_child4, 4);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_content_stretch_row_with_flex) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignContent(root, BNDYGAlignStretch);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root, 150);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexGrow(root_child1, 1);
  BNDYGNodeStyleSetFlexShrink(root_child1, 1);
  BNDYGNodeStyleSetFlexBasisPercent(root_child1, 0);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 50);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexGrow(root_child3, 1);
  BNDYGNodeStyleSetFlexShrink(root_child3, 1);
  BNDYGNodeStyleSetFlexBasisPercent(root_child3, 0);
  BNDYGNodeStyleSetWidth(root_child3, 50);
  BNDYGNodeInsertChild(root, root_child3, 3);

  const BNDYGNodeRef root_child4 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child4, 50);
  BNDYGNodeInsertChild(root, root_child4, 4);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_content_stretch_row_with_flex_no_shrink) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignContent(root, BNDYGAlignStretch);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root, 150);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexGrow(root_child1, 1);
  BNDYGNodeStyleSetFlexShrink(root_child1, 1);
  BNDYGNodeStyleSetFlexBasisPercent(root_child1, 0);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 50);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexGrow(root_child3, 1);
  BNDYGNodeStyleSetFlexBasisPercent(root_child3, 0);
  BNDYGNodeStyleSetWidth(root_child3, 50);
  BNDYGNodeInsertChild(root, root_child3, 3);

  const BNDYGNodeRef root_child4 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child4, 50);
  BNDYGNodeInsertChild(root, root_child4, 4);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_content_stretch_row_with_margin) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignContent(root, BNDYGAlignStretch);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root, 150);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetMargin(root_child1, BNDYGEdgeLeft, 10);
  BNDYGNodeStyleSetMargin(root_child1, BNDYGEdgeTop, 10);
  BNDYGNodeStyleSetMargin(root_child1, BNDYGEdgeRight, 10);
  BNDYGNodeStyleSetMargin(root_child1, BNDYGEdgeBottom, 10);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 50);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetMargin(root_child3, BNDYGEdgeLeft, 10);
  BNDYGNodeStyleSetMargin(root_child3, BNDYGEdgeTop, 10);
  BNDYGNodeStyleSetMargin(root_child3, BNDYGEdgeRight, 10);
  BNDYGNodeStyleSetMargin(root_child3, BNDYGEdgeBottom, 10);
  BNDYGNodeStyleSetWidth(root_child3, 50);
  BNDYGNodeInsertChild(root, root_child3, 3);

  const BNDYGNodeRef root_child4 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child4, 50);
  BNDYGNodeInsertChild(root, root_child4, 4);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_content_stretch_row_with_padding) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignContent(root, BNDYGAlignStretch);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root, 150);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetPadding(root_child1, BNDYGEdgeLeft, 10);
  BNDYGNodeStyleSetPadding(root_child1, BNDYGEdgeTop, 10);
  BNDYGNodeStyleSetPadding(root_child1, BNDYGEdgeRight, 10);
  BNDYGNodeStyleSetPadding(root_child1, BNDYGEdgeBottom, 10);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 50);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetPadding(root_child3, BNDYGEdgeLeft, 10);
  BNDYGNodeStyleSetPadding(root_child3, BNDYGEdgeTop, 10);
  BNDYGNodeStyleSetPadding(root_child3, BNDYGEdgeRight, 10);
  BNDYGNodeStyleSetPadding(root_child3, BNDYGEdgeBottom, 10);
  BNDYGNodeStyleSetWidth(root_child3, 50);
  BNDYGNodeInsertChild(root, root_child3, 3);

  const BNDYGNodeRef root_child4 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child4, 50);
  BNDYGNodeInsertChild(root, root_child4, 4);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_content_stretch_row_with_single_row) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignContent(root, BNDYGAlignStretch);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root, 150);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeInsertChild(root, root_child1, 1);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child1));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child1));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_content_stretch_row_with_fixed_height) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignContent(root, BNDYGAlignStretch);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root, 150);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeStyleSetHeight(root_child1, 60);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 50);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child3, 50);
  BNDYGNodeInsertChild(root, root_child3, 3);

  const BNDYGNodeRef root_child4 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child4, 50);
  BNDYGNodeInsertChild(root, root_child4, 4);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_content_stretch_row_with_max_height) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignContent(root, BNDYGAlignStretch);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root, 150);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeStyleSetMaxHeight(root_child1, 20);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 50);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child3, 50);
  BNDYGNodeInsertChild(root, root_child3, 3);

  const BNDYGNodeRef root_child4 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child4, 50);
  BNDYGNodeInsertChild(root, root_child4, 4);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_content_stretch_row_with_min_height) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignContent(root, BNDYGAlignStretch);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root, 150);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeStyleSetMinHeight(root_child1, 80);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 50);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child3, 50);
  BNDYGNodeInsertChild(root, root_child3, 3);

  const BNDYGNodeRef root_child4 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child4, 50);
  BNDYGNodeInsertChild(root, root_child4, 4);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(90, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(90, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(90, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(90, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(90, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(90, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(90, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(90, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(90, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(90, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_content_stretch_column) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetAlignContent(root, BNDYGAlignStretch);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root, 100);
  BNDYGNodeStyleSetHeight(root, 150);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetHeight(root_child0, 50);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child0_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexGrow(root_child0_child0, 1);
  BNDYGNodeStyleSetFlexShrink(root_child0_child0, 1);
  BNDYGNodeStyleSetFlexBasisPercent(root_child0_child0, 0);
  BNDYGNodeInsertChild(root_child0, root_child0_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexGrow(root_child1, 1);
  BNDYGNodeStyleSetFlexShrink(root_child1, 1);
  BNDYGNodeStyleSetFlexBasisPercent(root_child1, 0);
  BNDYGNodeStyleSetHeight(root_child1, 50);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetHeight(root_child2, 50);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetHeight(root_child3, 50);
  BNDYGNodeInsertChild(root, root_child3, 3);

  const BNDYGNodeRef root_child4 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetHeight(root_child4, 50);
  BNDYGNodeInsertChild(root, root_child4, 4);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_content_stretch_is_not_overriding_align_items) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetAlignContent(root, BNDYGAlignStretch);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root_child0, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignContent(root_child0, BNDYGAlignStretch);
  BNDYGNodeStyleSetAlignItems(root_child0, BNDYGAlignCenter);
  BNDYGNodeStyleSetWidth(root_child0, 100);
  BNDYGNodeStyleSetHeight(root_child0, 100);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child0_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetAlignContent(root_child0_child0, BNDYGAlignStretch);
  BNDYGNodeStyleSetWidth(root_child0_child0, 10);
  BNDYGNodeStyleSetHeight(root_child0_child0, 10);
  BNDYGNodeInsertChild(root_child0, root_child0_child0, 0);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(45, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0_child0));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(90, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(45, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0_child0));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}
