/**
 * Copyright (c) 2014-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @Generated by gentest/gentest.rb from gentest/fixtures/BNDYGAlignItemsTest.html

#include <gtest/gtest.h>
#include <bindyoga/BindYoga.h>

TEST(YogaTest, align_items_stretch) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root, 100);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetHeight(root_child0, 10);
  BNDYGNodeInsertChild(root, root_child0, 0);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_items_center) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignCenter);
  BNDYGNodeStyleSetWidth(root, 100);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 10);
  BNDYGNodeStyleSetHeight(root_child0, 10);
  BNDYGNodeInsertChild(root, root_child0, 0);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(45, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(45, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_items_flex_start) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignFlexStart);
  BNDYGNodeStyleSetWidth(root, 100);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 10);
  BNDYGNodeStyleSetHeight(root_child0, 10);
  BNDYGNodeInsertChild(root, root_child0, 0);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(90, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_items_flex_end) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignFlexEnd);
  BNDYGNodeStyleSetWidth(root, 100);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 10);
  BNDYGNodeStyleSetHeight(root_child0, 10);
  BNDYGNodeInsertChild(root, root_child0, 0);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(90, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_baseline) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignBaseline);
  BNDYGNodeStyleSetWidth(root, 100);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeStyleSetHeight(root_child0, 50);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeStyleSetHeight(root_child1, 20);
  BNDYGNodeInsertChild(root, root_child1, 1);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_baseline_child) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignBaseline);
  BNDYGNodeStyleSetWidth(root, 100);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeStyleSetHeight(root_child0, 50);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeStyleSetHeight(root_child1, 20);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child1_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1_child0, 50);
  BNDYGNodeStyleSetHeight(root_child1_child0, 10);
  BNDYGNodeInsertChild(root_child1, root_child1_child0, 0);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1_child0));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1_child0));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_baseline_child_multiline) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignBaseline);
  BNDYGNodeStyleSetWidth(root, 100);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeStyleSetHeight(root_child0, 60);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root_child1, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetFlexWrap(root_child1, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeStyleSetHeight(root_child1, 25);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child1_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1_child0, 25);
  BNDYGNodeStyleSetHeight(root_child1_child0, 20);
  BNDYGNodeInsertChild(root_child1, root_child1_child0, 0);

  const BNDYGNodeRef root_child1_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1_child1, 25);
  BNDYGNodeStyleSetHeight(root_child1_child1, 10);
  BNDYGNodeInsertChild(root_child1, root_child1_child1, 1);

  const BNDYGNodeRef root_child1_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1_child2, 25);
  BNDYGNodeStyleSetHeight(root_child1_child2, 20);
  BNDYGNodeInsertChild(root_child1, root_child1_child2, 2);

  const BNDYGNodeRef root_child1_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1_child3, 25);
  BNDYGNodeStyleSetHeight(root_child1_child3, 10);
  BNDYGNodeInsertChild(root_child1, root_child1_child3, 3);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1_child0));
  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetWidth(root_child1_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1_child0));

  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetLeft(root_child1_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1_child1));
  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetWidth(root_child1_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1_child2));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetTop(root_child1_child2));
  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetWidth(root_child1_child2));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1_child2));

  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetLeft(root_child1_child3));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetTop(root_child1_child3));
  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetWidth(root_child1_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1_child3));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetLeft(root_child1_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1_child0));
  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetWidth(root_child1_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1_child1));
  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetWidth(root_child1_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1_child1));

  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetLeft(root_child1_child2));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetTop(root_child1_child2));
  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetWidth(root_child1_child2));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1_child2));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1_child3));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetTop(root_child1_child3));
  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetWidth(root_child1_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1_child3));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_baseline_child_multiline_override) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignBaseline);
  BNDYGNodeStyleSetWidth(root, 100);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeStyleSetHeight(root_child0, 60);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root_child1, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetFlexWrap(root_child1, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeStyleSetHeight(root_child1, 25);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child1_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1_child0, 25);
  BNDYGNodeStyleSetHeight(root_child1_child0, 20);
  BNDYGNodeInsertChild(root_child1, root_child1_child0, 0);

  const BNDYGNodeRef root_child1_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetAlignSelf(root_child1_child1, BNDYGAlignBaseline);
  BNDYGNodeStyleSetWidth(root_child1_child1, 25);
  BNDYGNodeStyleSetHeight(root_child1_child1, 10);
  BNDYGNodeInsertChild(root_child1, root_child1_child1, 1);

  const BNDYGNodeRef root_child1_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1_child2, 25);
  BNDYGNodeStyleSetHeight(root_child1_child2, 20);
  BNDYGNodeInsertChild(root_child1, root_child1_child2, 2);

  const BNDYGNodeRef root_child1_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetAlignSelf(root_child1_child3, BNDYGAlignBaseline);
  BNDYGNodeStyleSetWidth(root_child1_child3, 25);
  BNDYGNodeStyleSetHeight(root_child1_child3, 10);
  BNDYGNodeInsertChild(root_child1, root_child1_child3, 3);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1_child0));
  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetWidth(root_child1_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1_child0));

  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetLeft(root_child1_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1_child1));
  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetWidth(root_child1_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1_child2));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetTop(root_child1_child2));
  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetWidth(root_child1_child2));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1_child2));

  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetLeft(root_child1_child3));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetTop(root_child1_child3));
  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetWidth(root_child1_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1_child3));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetLeft(root_child1_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1_child0));
  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetWidth(root_child1_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1_child1));
  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetWidth(root_child1_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1_child1));

  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetLeft(root_child1_child2));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetTop(root_child1_child2));
  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetWidth(root_child1_child2));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1_child2));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1_child3));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetTop(root_child1_child3));
  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetWidth(root_child1_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1_child3));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_baseline_child_multiline_no_override_on_secondline) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignBaseline);
  BNDYGNodeStyleSetWidth(root, 100);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeStyleSetHeight(root_child0, 60);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root_child1, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetFlexWrap(root_child1, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeStyleSetHeight(root_child1, 25);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child1_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1_child0, 25);
  BNDYGNodeStyleSetHeight(root_child1_child0, 20);
  BNDYGNodeInsertChild(root_child1, root_child1_child0, 0);

  const BNDYGNodeRef root_child1_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1_child1, 25);
  BNDYGNodeStyleSetHeight(root_child1_child1, 10);
  BNDYGNodeInsertChild(root_child1, root_child1_child1, 1);

  const BNDYGNodeRef root_child1_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1_child2, 25);
  BNDYGNodeStyleSetHeight(root_child1_child2, 20);
  BNDYGNodeInsertChild(root_child1, root_child1_child2, 2);

  const BNDYGNodeRef root_child1_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetAlignSelf(root_child1_child3, BNDYGAlignBaseline);
  BNDYGNodeStyleSetWidth(root_child1_child3, 25);
  BNDYGNodeStyleSetHeight(root_child1_child3, 10);
  BNDYGNodeInsertChild(root_child1, root_child1_child3, 3);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1_child0));
  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetWidth(root_child1_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1_child0));

  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetLeft(root_child1_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1_child1));
  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetWidth(root_child1_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1_child2));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetTop(root_child1_child2));
  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetWidth(root_child1_child2));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1_child2));

  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetLeft(root_child1_child3));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetTop(root_child1_child3));
  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetWidth(root_child1_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1_child3));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetLeft(root_child1_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1_child0));
  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetWidth(root_child1_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1_child1));
  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetWidth(root_child1_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1_child1));

  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetLeft(root_child1_child2));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetTop(root_child1_child2));
  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetWidth(root_child1_child2));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1_child2));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1_child3));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetTop(root_child1_child3));
  ASSERT_FLOAT_EQ(25, BNDYGNodeLayoutGetWidth(root_child1_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1_child3));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_baseline_child_top) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignBaseline);
  BNDYGNodeStyleSetWidth(root, 100);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetPosition(root_child0, BNDYGEdgeTop, 10);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeStyleSetHeight(root_child0, 50);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeStyleSetHeight(root_child1, 20);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child1_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1_child0, 50);
  BNDYGNodeStyleSetHeight(root_child1_child0, 10);
  BNDYGNodeInsertChild(root_child1, root_child1_child0, 0);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1_child0));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1_child0));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_baseline_child_top2) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignBaseline);
  BNDYGNodeStyleSetWidth(root, 100);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeStyleSetHeight(root_child0, 50);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetPosition(root_child1, BNDYGEdgeTop, 5);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeStyleSetHeight(root_child1, 20);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child1_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1_child0, 50);
  BNDYGNodeStyleSetHeight(root_child1_child0, 10);
  BNDYGNodeInsertChild(root_child1, root_child1_child0, 0);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(45, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1_child0));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(45, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1_child0));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_baseline_double_nested_child) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignBaseline);
  BNDYGNodeStyleSetWidth(root, 100);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeStyleSetHeight(root_child0, 50);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child0_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0_child0, 50);
  BNDYGNodeStyleSetHeight(root_child0_child0, 20);
  BNDYGNodeInsertChild(root_child0, root_child0_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeStyleSetHeight(root_child1, 20);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child1_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1_child0, 50);
  BNDYGNodeStyleSetHeight(root_child1_child0, 15);
  BNDYGNodeInsertChild(root_child1, root_child1_child0, 0);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(5, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1_child0));
  ASSERT_FLOAT_EQ(15, BNDYGNodeLayoutGetHeight(root_child1_child0));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(5, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1_child0));
  ASSERT_FLOAT_EQ(15, BNDYGNodeLayoutGetHeight(root_child1_child0));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_baseline_column) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignBaseline);
  BNDYGNodeStyleSetWidth(root, 100);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeStyleSetHeight(root_child0, 50);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeStyleSetHeight(root_child1, 20);
  BNDYGNodeInsertChild(root, root_child1, 1);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_baseline_child_margin) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignBaseline);
  BNDYGNodeStyleSetWidth(root, 100);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetMargin(root_child0, BNDYGEdgeLeft, 5);
  BNDYGNodeStyleSetMargin(root_child0, BNDYGEdgeTop, 5);
  BNDYGNodeStyleSetMargin(root_child0, BNDYGEdgeRight, 5);
  BNDYGNodeStyleSetMargin(root_child0, BNDYGEdgeBottom, 5);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeStyleSetHeight(root_child0, 50);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeStyleSetHeight(root_child1, 20);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child1_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetMargin(root_child1_child0, BNDYGEdgeLeft, 1);
  BNDYGNodeStyleSetMargin(root_child1_child0, BNDYGEdgeTop, 1);
  BNDYGNodeStyleSetMargin(root_child1_child0, BNDYGEdgeRight, 1);
  BNDYGNodeStyleSetMargin(root_child1_child0, BNDYGEdgeBottom, 1);
  BNDYGNodeStyleSetWidth(root_child1_child0, 50);
  BNDYGNodeStyleSetHeight(root_child1_child0, 10);
  BNDYGNodeInsertChild(root_child1, root_child1_child0, 0);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(5, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(5, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(44, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(1, BNDYGNodeLayoutGetLeft(root_child1_child0));
  ASSERT_FLOAT_EQ(1, BNDYGNodeLayoutGetTop(root_child1_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1_child0));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(45, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(5, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(-10, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(44, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(-1, BNDYGNodeLayoutGetLeft(root_child1_child0));
  ASSERT_FLOAT_EQ(1, BNDYGNodeLayoutGetTop(root_child1_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1_child0));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_baseline_child_padding) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignBaseline);
  BNDYGNodeStyleSetPadding(root, BNDYGEdgeLeft, 5);
  BNDYGNodeStyleSetPadding(root, BNDYGEdgeTop, 5);
  BNDYGNodeStyleSetPadding(root, BNDYGEdgeRight, 5);
  BNDYGNodeStyleSetPadding(root, BNDYGEdgeBottom, 5);
  BNDYGNodeStyleSetWidth(root, 100);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeStyleSetHeight(root_child0, 50);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetPadding(root_child1, BNDYGEdgeLeft, 5);
  BNDYGNodeStyleSetPadding(root_child1, BNDYGEdgeTop, 5);
  BNDYGNodeStyleSetPadding(root_child1, BNDYGEdgeRight, 5);
  BNDYGNodeStyleSetPadding(root_child1, BNDYGEdgeBottom, 5);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeStyleSetHeight(root_child1, 20);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child1_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1_child0, 50);
  BNDYGNodeStyleSetHeight(root_child1_child0, 10);
  BNDYGNodeInsertChild(root_child1, root_child1_child0, 0);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(5, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(5, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(55, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(5, BNDYGNodeLayoutGetLeft(root_child1_child0));
  ASSERT_FLOAT_EQ(5, BNDYGNodeLayoutGetTop(root_child1_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1_child0));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(45, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(5, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(-5, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(-5, BNDYGNodeLayoutGetLeft(root_child1_child0));
  ASSERT_FLOAT_EQ(5, BNDYGNodeLayoutGetTop(root_child1_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1_child0));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_baseline_multiline) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignBaseline);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root, 100);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeStyleSetHeight(root_child0, 50);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeStyleSetHeight(root_child1, 20);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child1_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1_child0, 50);
  BNDYGNodeStyleSetHeight(root_child1_child0, 10);
  BNDYGNodeInsertChild(root_child1, root_child1_child0, 0);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 50);
  BNDYGNodeStyleSetHeight(root_child2, 20);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child2_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2_child0, 50);
  BNDYGNodeStyleSetHeight(root_child2_child0, 10);
  BNDYGNodeInsertChild(root_child2, root_child2_child0, 0);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child3, 50);
  BNDYGNodeStyleSetHeight(root_child3, 50);
  BNDYGNodeInsertChild(root, root_child3, 3);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child2_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child3));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child2_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child3));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_baseline_multiline_column) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignBaseline);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root, 100);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeStyleSetHeight(root_child0, 50);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 30);
  BNDYGNodeStyleSetHeight(root_child1, 50);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child1_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1_child0, 20);
  BNDYGNodeStyleSetHeight(root_child1_child0, 20);
  BNDYGNodeInsertChild(root_child1, root_child1_child0, 0);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 40);
  BNDYGNodeStyleSetHeight(root_child2, 70);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child2_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2_child0, 10);
  BNDYGNodeStyleSetHeight(root_child2_child0, 10);
  BNDYGNodeInsertChild(root_child2, root_child2_child0, 0);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child3, 50);
  BNDYGNodeStyleSetHeight(root_child3, 20);
  BNDYGNodeInsertChild(root, root_child3, 3);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetWidth(root_child1_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child2_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child2_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child3));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetLeft(root_child1_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetWidth(root_child1_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1_child0));

  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetLeft(root_child2_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child2_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child2_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child3));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_baseline_multiline_column2) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignBaseline);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root, 100);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeStyleSetHeight(root_child0, 50);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 30);
  BNDYGNodeStyleSetHeight(root_child1, 50);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child1_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1_child0, 20);
  BNDYGNodeStyleSetHeight(root_child1_child0, 20);
  BNDYGNodeInsertChild(root_child1, root_child1_child0, 0);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 40);
  BNDYGNodeStyleSetHeight(root_child2, 70);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child2_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2_child0, 10);
  BNDYGNodeStyleSetHeight(root_child2_child0, 10);
  BNDYGNodeInsertChild(root_child2, root_child2_child0, 0);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child3, 50);
  BNDYGNodeStyleSetHeight(root_child3, 20);
  BNDYGNodeInsertChild(root, root_child3, 3);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetWidth(root_child1_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child2_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child2_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child3));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetLeft(root_child1_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetWidth(root_child1_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1_child0));

  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetLeft(root_child2_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child2_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child2_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child3));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_baseline_multiline_row_and_column) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignBaseline);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root, 100);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeStyleSetHeight(root_child0, 50);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeStyleSetHeight(root_child1, 50);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child1_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1_child0, 50);
  BNDYGNodeStyleSetHeight(root_child1_child0, 10);
  BNDYGNodeInsertChild(root_child1, root_child1_child0, 0);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 50);
  BNDYGNodeStyleSetHeight(root_child2, 20);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child2_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2_child0, 50);
  BNDYGNodeStyleSetHeight(root_child2_child0, 10);
  BNDYGNodeInsertChild(root_child2, root_child2_child0, 0);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child3, 50);
  BNDYGNodeStyleSetHeight(root_child3, 20);
  BNDYGNodeInsertChild(root, root_child3, 3);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child2_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(90, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child3));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child2_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child2_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(90, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child3));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_items_center_child_with_margin_bigger_than_parent) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetJustifyContent(root, BNDYGJustifyCenter);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignCenter);
  BNDYGNodeStyleSetWidth(root, 52);
  BNDYGNodeStyleSetHeight(root, 52);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetAlignItems(root_child0, BNDYGAlignCenter);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child0_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetMargin(root_child0_child0, BNDYGEdgeLeft, 10);
  BNDYGNodeStyleSetMargin(root_child0_child0, BNDYGEdgeRight, 10);
  BNDYGNodeStyleSetWidth(root_child0_child0, 52);
  BNDYGNodeStyleSetHeight(root_child0_child0, 52);
  BNDYGNodeInsertChild(root_child0, root_child0_child0, 0);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(52, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(52, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(-10, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(72, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(52, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(52, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(52, BNDYGNodeLayoutGetHeight(root_child0_child0));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(52, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(52, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(-10, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(72, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(52, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(52, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(52, BNDYGNodeLayoutGetHeight(root_child0_child0));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_items_flex_end_child_with_margin_bigger_than_parent) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetJustifyContent(root, BNDYGJustifyCenter);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignCenter);
  BNDYGNodeStyleSetWidth(root, 52);
  BNDYGNodeStyleSetHeight(root, 52);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetAlignItems(root_child0, BNDYGAlignFlexEnd);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child0_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetMargin(root_child0_child0, BNDYGEdgeLeft, 10);
  BNDYGNodeStyleSetMargin(root_child0_child0, BNDYGEdgeRight, 10);
  BNDYGNodeStyleSetWidth(root_child0_child0, 52);
  BNDYGNodeStyleSetHeight(root_child0_child0, 52);
  BNDYGNodeInsertChild(root_child0, root_child0_child0, 0);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(52, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(52, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(-10, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(72, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(52, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(52, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(52, BNDYGNodeLayoutGetHeight(root_child0_child0));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(52, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(52, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(-10, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(72, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(52, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(52, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(52, BNDYGNodeLayoutGetHeight(root_child0_child0));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_items_center_child_without_margin_bigger_than_parent) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetJustifyContent(root, BNDYGJustifyCenter);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignCenter);
  BNDYGNodeStyleSetWidth(root, 52);
  BNDYGNodeStyleSetHeight(root, 52);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetAlignItems(root_child0, BNDYGAlignCenter);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child0_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0_child0, 72);
  BNDYGNodeStyleSetHeight(root_child0_child0, 72);
  BNDYGNodeInsertChild(root_child0, root_child0_child0, 0);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(52, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(52, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(-10, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(-10, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(72, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(72, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(72, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(72, BNDYGNodeLayoutGetHeight(root_child0_child0));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(52, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(52, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(-10, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(-10, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(72, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(72, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(72, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(72, BNDYGNodeLayoutGetHeight(root_child0_child0));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_items_flex_end_child_without_margin_bigger_than_parent) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetJustifyContent(root, BNDYGJustifyCenter);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignCenter);
  BNDYGNodeStyleSetWidth(root, 52);
  BNDYGNodeStyleSetHeight(root, 52);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetAlignItems(root_child0, BNDYGAlignFlexEnd);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child0_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0_child0, 72);
  BNDYGNodeStyleSetHeight(root_child0_child0, 72);
  BNDYGNodeInsertChild(root_child0, root_child0_child0, 0);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(52, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(52, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(-10, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(-10, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(72, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(72, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(72, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(72, BNDYGNodeLayoutGetHeight(root_child0_child0));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(52, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(52, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(-10, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(-10, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(72, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(72, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(72, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(72, BNDYGNodeLayoutGetHeight(root_child0_child0));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_center_should_size_based_on_content) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignCenter);
  BNDYGNodeStyleSetMargin(root, BNDYGEdgeTop, 20);
  BNDYGNodeStyleSetWidth(root, 100);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetJustifyContent(root_child0, BNDYGJustifyCenter);
  BNDYGNodeStyleSetFlexShrink(root_child0, 1);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child0_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexGrow(root_child0_child0, 1);
  BNDYGNodeStyleSetFlexShrink(root_child0_child0, 1);
  BNDYGNodeInsertChild(root_child0, root_child0_child0, 0);

  const BNDYGNodeRef root_child0_child0_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0_child0_child0, 20);
  BNDYGNodeStyleSetHeight(root_child0_child0_child0, 20);
  BNDYGNodeInsertChild(root_child0_child0, root_child0_child0_child0, 0);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetWidth(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child0_child0_child0));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetWidth(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child0_child0_child0));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_strech_should_size_based_on_parent) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetMargin(root, BNDYGEdgeTop, 20);
  BNDYGNodeStyleSetWidth(root, 100);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetJustifyContent(root_child0, BNDYGJustifyCenter);
  BNDYGNodeStyleSetFlexShrink(root_child0, 1);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child0_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexGrow(root_child0_child0, 1);
  BNDYGNodeStyleSetFlexShrink(root_child0_child0, 1);
  BNDYGNodeInsertChild(root_child0, root_child0_child0, 0);

  const BNDYGNodeRef root_child0_child0_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0_child0_child0, 20);
  BNDYGNodeStyleSetHeight(root_child0_child0_child0, 20);
  BNDYGNodeInsertChild(root_child0_child0, root_child0_child0_child0, 0);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetWidth(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child0_child0_child0));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetLeft(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetWidth(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child0_child0_child0));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_flex_start_with_shrinking_children) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root, 500);
  BNDYGNodeStyleSetHeight(root, 500);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetAlignItems(root_child0, BNDYGAlignFlexStart);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child0_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexGrow(root_child0_child0, 1);
  BNDYGNodeStyleSetFlexShrink(root_child0_child0, 1);
  BNDYGNodeInsertChild(root_child0, root_child0_child0, 0);

  const BNDYGNodeRef root_child0_child0_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexGrow(root_child0_child0_child0, 1);
  BNDYGNodeStyleSetFlexShrink(root_child0_child0_child0, 1);
  BNDYGNodeInsertChild(root_child0_child0, root_child0_child0_child0, 0);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetWidth(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child0_child0_child0));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetWidth(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child0_child0_child0));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_flex_start_with_stretching_children) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root, 500);
  BNDYGNodeStyleSetHeight(root, 500);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child0_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexGrow(root_child0_child0, 1);
  BNDYGNodeStyleSetFlexShrink(root_child0_child0, 1);
  BNDYGNodeInsertChild(root_child0, root_child0_child0, 0);

  const BNDYGNodeRef root_child0_child0_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexGrow(root_child0_child0_child0, 1);
  BNDYGNodeStyleSetFlexShrink(root_child0_child0_child0, 1);
  BNDYGNodeInsertChild(root_child0_child0, root_child0_child0_child0, 0);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetWidth(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child0_child0_child0));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetWidth(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child0_child0_child0));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, align_flex_start_with_shrinking_children_with_stretch) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root, 500);
  BNDYGNodeStyleSetHeight(root, 500);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetAlignItems(root_child0, BNDYGAlignFlexStart);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child0_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexGrow(root_child0_child0, 1);
  BNDYGNodeStyleSetFlexShrink(root_child0_child0, 1);
  BNDYGNodeInsertChild(root_child0, root_child0_child0, 0);

  const BNDYGNodeRef root_child0_child0_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexGrow(root_child0_child0_child0, 1);
  BNDYGNodeStyleSetFlexShrink(root_child0_child0_child0, 1);
  BNDYGNodeInsertChild(root_child0_child0, root_child0_child0_child0, 0);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetWidth(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child0_child0_child0));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetWidth(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetHeight(root_child0_child0_child0));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}
