/**
 * Copyright (c) 2014-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @Generated by gentest/gentest.rb from gentest/fixtures/BNDYGFlexWrapTest.html

#include <gtest/gtest.h>
#include <bindyoga/BindYoga.h>

TEST(YogaTest, wrap_column) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrap);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 30);
  BNDYGNodeStyleSetHeight(root_child0, 30);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 30);
  BNDYGNodeStyleSetHeight(root_child1, 30);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 30);
  BNDYGNodeStyleSetHeight(root_child2, 30);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child3, 30);
  BNDYGNodeStyleSetHeight(root_child3, 30);
  BNDYGNodeInsertChild(root, root_child3, 3);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child3));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child3));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, wrap_row) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 30);
  BNDYGNodeStyleSetHeight(root_child0, 30);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 30);
  BNDYGNodeStyleSetHeight(root_child1, 30);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 30);
  BNDYGNodeStyleSetHeight(root_child2, 30);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child3, 30);
  BNDYGNodeStyleSetHeight(root_child3, 30);
  BNDYGNodeInsertChild(root, root_child3, 3);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child3));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child3));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, wrap_row_align_items_flex_end) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignFlexEnd);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 30);
  BNDYGNodeStyleSetHeight(root_child0, 10);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 30);
  BNDYGNodeStyleSetHeight(root_child1, 20);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 30);
  BNDYGNodeStyleSetHeight(root_child2, 30);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child3, 30);
  BNDYGNodeStyleSetHeight(root_child3, 30);
  BNDYGNodeInsertChild(root, root_child3, 3);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child3));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child3));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, wrap_row_align_items_center) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignCenter);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 30);
  BNDYGNodeStyleSetHeight(root_child0, 10);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 30);
  BNDYGNodeStyleSetHeight(root_child1, 20);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 30);
  BNDYGNodeStyleSetHeight(root_child2, 30);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child3, 30);
  BNDYGNodeStyleSetHeight(root_child3, 30);
  BNDYGNodeInsertChild(root, root_child3, 3);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(5, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child3));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(5, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child3));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, flex_wrap_children_with_min_main_overriding_flex_basis) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexBasis(root_child0, 50);
  BNDYGNodeStyleSetMinWidth(root_child0, 55);
  BNDYGNodeStyleSetHeight(root_child0, 50);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexBasis(root_child1, 50);
  BNDYGNodeStyleSetMinWidth(root_child1, 55);
  BNDYGNodeStyleSetHeight(root_child1, 50);
  BNDYGNodeInsertChild(root, root_child1, 1);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(55, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(55, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child1));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(45, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(55, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(45, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(55, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child1));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, flex_wrap_wrap_to_child_height) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root_child0, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignItems(root_child0, BNDYGAlignFlexStart);
  BNDYGNodeStyleSetFlexWrap(root_child0, BNDYGWrapWrap);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child0_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0_child0, 100);
  BNDYGNodeInsertChild(root_child0, root_child0_child0, 0);

  const BNDYGNodeRef root_child0_child0_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0_child0_child0, 100);
  BNDYGNodeStyleSetHeight(root_child0_child0_child0, 100);
  BNDYGNodeInsertChild(root_child0_child0, root_child0_child0_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 100);
  BNDYGNodeStyleSetHeight(root_child1, 100);
  BNDYGNodeInsertChild(root, root_child1, 1);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child0_child0_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child1));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child0_child0_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child1));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, flex_wrap_align_stretch_fits_one_row) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root, 150);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 50);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 50);
  BNDYGNodeInsertChild(root, root_child1, 1);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child1));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child1));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, wrap_reverse_row_align_content_flex_start) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrapReverse);
  BNDYGNodeStyleSetWidth(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 30);
  BNDYGNodeStyleSetHeight(root_child0, 10);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 30);
  BNDYGNodeStyleSetHeight(root_child1, 20);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 30);
  BNDYGNodeStyleSetHeight(root_child2, 30);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child3, 30);
  BNDYGNodeStyleSetHeight(root_child3, 40);
  BNDYGNodeInsertChild(root, root_child3, 3);

  const BNDYGNodeRef root_child4 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child4, 30);
  BNDYGNodeStyleSetHeight(root_child4, 50);
  BNDYGNodeInsertChild(root, root_child4, 4);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, wrap_reverse_row_align_content_center) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignContent(root, BNDYGAlignCenter);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrapReverse);
  BNDYGNodeStyleSetWidth(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 30);
  BNDYGNodeStyleSetHeight(root_child0, 10);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 30);
  BNDYGNodeStyleSetHeight(root_child1, 20);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 30);
  BNDYGNodeStyleSetHeight(root_child2, 30);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child3, 30);
  BNDYGNodeStyleSetHeight(root_child3, 40);
  BNDYGNodeInsertChild(root, root_child3, 3);

  const BNDYGNodeRef root_child4 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child4, 30);
  BNDYGNodeStyleSetHeight(root_child4, 50);
  BNDYGNodeInsertChild(root, root_child4, 4);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, wrap_reverse_row_single_line_different_size) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrapReverse);
  BNDYGNodeStyleSetWidth(root, 300);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 30);
  BNDYGNodeStyleSetHeight(root_child0, 10);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 30);
  BNDYGNodeStyleSetHeight(root_child1, 20);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 30);
  BNDYGNodeStyleSetHeight(root_child2, 30);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child3, 30);
  BNDYGNodeStyleSetHeight(root_child3, 40);
  BNDYGNodeInsertChild(root, root_child3, 3);

  const BNDYGNodeRef root_child4 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child4, 30);
  BNDYGNodeStyleSetHeight(root_child4, 50);
  BNDYGNodeInsertChild(root, root_child4, 4);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(300, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(90, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(120, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(300, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(270, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(240, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(210, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(180, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, wrap_reverse_row_align_content_stretch) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignContent(root, BNDYGAlignStretch);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrapReverse);
  BNDYGNodeStyleSetWidth(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 30);
  BNDYGNodeStyleSetHeight(root_child0, 10);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 30);
  BNDYGNodeStyleSetHeight(root_child1, 20);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 30);
  BNDYGNodeStyleSetHeight(root_child2, 30);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child3, 30);
  BNDYGNodeStyleSetHeight(root_child3, 40);
  BNDYGNodeInsertChild(root, root_child3, 3);

  const BNDYGNodeRef root_child4 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child4, 30);
  BNDYGNodeStyleSetHeight(root_child4, 50);
  BNDYGNodeInsertChild(root, root_child4, 4);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, wrap_reverse_row_align_content_space_around) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetAlignContent(root, BNDYGAlignSpaceAround);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrapReverse);
  BNDYGNodeStyleSetWidth(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 30);
  BNDYGNodeStyleSetHeight(root_child0, 10);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 30);
  BNDYGNodeStyleSetHeight(root_child1, 20);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 30);
  BNDYGNodeStyleSetHeight(root_child2, 30);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child3, 30);
  BNDYGNodeStyleSetHeight(root_child3, 40);
  BNDYGNodeInsertChild(root, root_child3, 3);

  const BNDYGNodeRef root_child4 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child4, 30);
  BNDYGNodeStyleSetHeight(root_child4, 50);
  BNDYGNodeInsertChild(root, root_child4, 4);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, wrap_reverse_column_fixed_size) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignCenter);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrapReverse);
  BNDYGNodeStyleSetWidth(root, 200);
  BNDYGNodeStyleSetHeight(root, 100);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 30);
  BNDYGNodeStyleSetHeight(root_child0, 10);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 30);
  BNDYGNodeStyleSetHeight(root_child1, 20);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 30);
  BNDYGNodeStyleSetHeight(root_child2, 30);
  BNDYGNodeInsertChild(root, root_child2, 2);

  const BNDYGNodeRef root_child3 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child3, 30);
  BNDYGNodeStyleSetHeight(root_child3, 40);
  BNDYGNodeInsertChild(root, root_child3, 3);

  const BNDYGNodeRef root_child4 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child4, 30);
  BNDYGNodeStyleSetHeight(root_child4, 50);
  BNDYGNodeInsertChild(root, root_child4, 4);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(170, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(170, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(170, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(170, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(140, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(60, BNDYGNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root_child4));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, wrapped_row_within_align_items_center) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignCenter);
  BNDYGNodeStyleSetWidth(root, 200);
  BNDYGNodeStyleSetHeight(root, 200);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root_child0, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetFlexWrap(root_child0, BNDYGWrapWrap);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child0_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0_child0, 150);
  BNDYGNodeStyleSetHeight(root_child0_child0, 80);
  BNDYGNodeInsertChild(root_child0, root_child0_child0, 0);

  const BNDYGNodeRef root_child0_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0_child1, 80);
  BNDYGNodeStyleSetHeight(root_child0_child1, 80);
  BNDYGNodeInsertChild(root_child0, root_child0_child1, 1);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(160, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child1));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetTop(root_child0_child1));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetWidth(root_child0_child1));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetHeight(root_child0_child1));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(160, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(120, BNDYGNodeLayoutGetLeft(root_child0_child1));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetTop(root_child0_child1));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetWidth(root_child0_child1));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetHeight(root_child0_child1));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, wrapped_row_within_align_items_flex_start) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignFlexStart);
  BNDYGNodeStyleSetWidth(root, 200);
  BNDYGNodeStyleSetHeight(root, 200);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root_child0, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetFlexWrap(root_child0, BNDYGWrapWrap);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child0_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0_child0, 150);
  BNDYGNodeStyleSetHeight(root_child0_child0, 80);
  BNDYGNodeInsertChild(root_child0, root_child0_child0, 0);

  const BNDYGNodeRef root_child0_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0_child1, 80);
  BNDYGNodeStyleSetHeight(root_child0_child1, 80);
  BNDYGNodeInsertChild(root_child0, root_child0_child1, 1);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(160, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child1));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetTop(root_child0_child1));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetWidth(root_child0_child1));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetHeight(root_child0_child1));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(160, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(120, BNDYGNodeLayoutGetLeft(root_child0_child1));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetTop(root_child0_child1));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetWidth(root_child0_child1));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetHeight(root_child0_child1));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, wrapped_row_within_align_items_flex_end) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignFlexEnd);
  BNDYGNodeStyleSetWidth(root, 200);
  BNDYGNodeStyleSetHeight(root, 200);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root_child0, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetFlexWrap(root_child0, BNDYGWrapWrap);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child0_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0_child0, 150);
  BNDYGNodeStyleSetHeight(root_child0_child0, 80);
  BNDYGNodeInsertChild(root_child0, root_child0_child0, 0);

  const BNDYGNodeRef root_child0_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0_child1, 80);
  BNDYGNodeStyleSetHeight(root_child0_child1, 80);
  BNDYGNodeInsertChild(root_child0, root_child0_child1, 1);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(160, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child1));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetTop(root_child0_child1));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetWidth(root_child0_child1));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetHeight(root_child0_child1));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(160, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(150, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(120, BNDYGNodeLayoutGetLeft(root_child0_child1));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetTop(root_child0_child1));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetWidth(root_child0_child1));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetHeight(root_child0_child1));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, wrapped_column_max_height) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetJustifyContent(root, BNDYGJustifyCenter);
  BNDYGNodeStyleSetAlignContent(root, BNDYGAlignCenter);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignCenter);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root, 700);
  BNDYGNodeStyleSetHeight(root, 500);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 100);
  BNDYGNodeStyleSetHeight(root_child0, 500);
  BNDYGNodeStyleSetMaxHeight(root_child0, 200);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetMargin(root_child1, BNDYGEdgeLeft, 20);
  BNDYGNodeStyleSetMargin(root_child1, BNDYGEdgeTop, 20);
  BNDYGNodeStyleSetMargin(root_child1, BNDYGEdgeRight, 20);
  BNDYGNodeStyleSetMargin(root_child1, BNDYGEdgeBottom, 20);
  BNDYGNodeStyleSetWidth(root_child1, 200);
  BNDYGNodeStyleSetHeight(root_child1, 200);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 100);
  BNDYGNodeStyleSetHeight(root_child2, 100);
  BNDYGNodeInsertChild(root, root_child2, 2);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(700, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(250, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(250, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(420, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child2));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(700, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(350, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(300, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(250, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(180, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child2));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, wrapped_column_max_height_flex) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetJustifyContent(root, BNDYGJustifyCenter);
  BNDYGNodeStyleSetAlignContent(root, BNDYGAlignCenter);
  BNDYGNodeStyleSetAlignItems(root, BNDYGAlignCenter);
  BNDYGNodeStyleSetFlexWrap(root, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root, 700);
  BNDYGNodeStyleSetHeight(root, 500);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexGrow(root_child0, 1);
  BNDYGNodeStyleSetFlexShrink(root_child0, 1);
  BNDYGNodeStyleSetFlexBasisPercent(root_child0, 0);
  BNDYGNodeStyleSetWidth(root_child0, 100);
  BNDYGNodeStyleSetHeight(root_child0, 500);
  BNDYGNodeStyleSetMaxHeight(root_child0, 200);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexGrow(root_child1, 1);
  BNDYGNodeStyleSetFlexShrink(root_child1, 1);
  BNDYGNodeStyleSetFlexBasisPercent(root_child1, 0);
  BNDYGNodeStyleSetMargin(root_child1, BNDYGEdgeLeft, 20);
  BNDYGNodeStyleSetMargin(root_child1, BNDYGEdgeTop, 20);
  BNDYGNodeStyleSetMargin(root_child1, BNDYGEdgeRight, 20);
  BNDYGNodeStyleSetMargin(root_child1, BNDYGEdgeBottom, 20);
  BNDYGNodeStyleSetWidth(root_child1, 200);
  BNDYGNodeStyleSetHeight(root_child1, 200);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 100);
  BNDYGNodeStyleSetHeight(root_child2, 100);
  BNDYGNodeInsertChild(root, root_child2, 2);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(700, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(300, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(180, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(250, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(180, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(300, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(400, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child2));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(700, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(300, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(180, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(250, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(200, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(180, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(300, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(400, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetHeight(root_child2));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, wrap_nodes_with_content_sizing_overflowing_margin) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root, 500);
  BNDYGNodeStyleSetHeight(root, 500);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root_child0, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetFlexWrap(root_child0, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root_child0, 85);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child0_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeInsertChild(root_child0, root_child0_child0, 0);

  const BNDYGNodeRef root_child0_child0_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0_child0_child0, 40);
  BNDYGNodeStyleSetHeight(root_child0_child0_child0, 40);
  BNDYGNodeInsertChild(root_child0_child0, root_child0_child0_child0, 0);

  const BNDYGNodeRef root_child0_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetMargin(root_child0_child1, BNDYGEdgeRight, 10);
  BNDYGNodeInsertChild(root_child0, root_child0_child1, 1);

  const BNDYGNodeRef root_child0_child1_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0_child1_child0, 40);
  BNDYGNodeStyleSetHeight(root_child0_child1_child0, 40);
  BNDYGNodeInsertChild(root_child0_child1, root_child0_child1_child0, 0);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(85, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetWidth(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child0_child0_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child1));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetTop(root_child0_child1));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetWidth(root_child0_child1));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child0_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child1_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child1_child0));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetWidth(root_child0_child1_child0));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child0_child1_child0));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(415, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(85, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(45, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetWidth(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child0_child0_child0));

  ASSERT_FLOAT_EQ(35, BNDYGNodeLayoutGetLeft(root_child0_child1));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetTop(root_child0_child1));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetWidth(root_child0_child1));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child0_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child1_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child1_child0));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetWidth(root_child0_child1_child0));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child0_child1_child0));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, wrap_nodes_with_content_sizing_margin_cross) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root, 500);
  BNDYGNodeStyleSetHeight(root, 500);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root_child0, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetFlexWrap(root_child0, BNDYGWrapWrap);
  BNDYGNodeStyleSetWidth(root_child0, 70);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child0_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeInsertChild(root_child0, root_child0_child0, 0);

  const BNDYGNodeRef root_child0_child0_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0_child0_child0, 40);
  BNDYGNodeStyleSetHeight(root_child0_child0_child0, 40);
  BNDYGNodeInsertChild(root_child0_child0, root_child0_child0_child0, 0);

  const BNDYGNodeRef root_child0_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetMargin(root_child0_child1, BNDYGEdgeTop, 10);
  BNDYGNodeInsertChild(root_child0, root_child0_child1, 1);

  const BNDYGNodeRef root_child0_child1_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0_child1_child0, 40);
  BNDYGNodeStyleSetHeight(root_child0_child1_child0, 40);
  BNDYGNodeInsertChild(root_child0_child1, root_child0_child1_child0, 0);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(90, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetWidth(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child0_child0_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child0_child1));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetWidth(root_child0_child1));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child0_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child1_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child1_child0));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetWidth(root_child0_child1_child0));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child0_child1_child0));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(500, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(430, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(70, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(90, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetWidth(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child0_child0_child0));

  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetLeft(root_child0_child1));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetTop(root_child0_child1));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetWidth(root_child0_child1));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child0_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0_child1_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0_child1_child0));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetWidth(root_child0_child1_child0));
  ASSERT_FLOAT_EQ(40, BNDYGNodeLayoutGetHeight(root_child0_child1_child0));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}
