/**
 * Copyright (c) 2014-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @Generated by gentest/gentest.rb from gentest/fixtures/BNDYGJustifyContentTest.html

#include <gtest/gtest.h>
#include <bindyoga/BindYoga.h>

TEST(YogaTest, justify_content_row_flex_start) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetWidth(root, 102);
  BNDYGNodeStyleSetHeight(root, 102);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 10);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 10);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 10);
  BNDYGNodeInsertChild(root, root_child2, 2);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root_child2));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(92, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(82, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(72, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root_child2));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, justify_content_row_flex_end) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetJustifyContent(root, BNDYGJustifyFlexEnd);
  BNDYGNodeStyleSetWidth(root, 102);
  BNDYGNodeStyleSetHeight(root, 102);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 10);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 10);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 10);
  BNDYGNodeInsertChild(root, root_child2, 2);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(72, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(82, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(92, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root_child2));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root_child2));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, justify_content_row_center) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetJustifyContent(root, BNDYGJustifyCenter);
  BNDYGNodeStyleSetWidth(root, 102);
  BNDYGNodeStyleSetHeight(root, 102);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 10);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 10);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 10);
  BNDYGNodeInsertChild(root, root_child2, 2);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(36, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(46, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(56, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root_child2));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(56, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(46, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(36, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root_child2));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, justify_content_row_space_between) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetJustifyContent(root, BNDYGJustifySpaceBetween);
  BNDYGNodeStyleSetWidth(root, 102);
  BNDYGNodeStyleSetHeight(root, 102);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 10);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 10);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 10);
  BNDYGNodeInsertChild(root, root_child2, 2);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(46, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(92, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root_child2));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(92, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(46, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root_child2));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, justify_content_row_space_around) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetJustifyContent(root, BNDYGJustifySpaceAround);
  BNDYGNodeStyleSetWidth(root, 102);
  BNDYGNodeStyleSetHeight(root, 102);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 10);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child1, 10);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child2, 10);
  BNDYGNodeInsertChild(root, root_child2, 2);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(12, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(46, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root_child2));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(46, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(12, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root_child2));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, justify_content_column_flex_start) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root, 102);
  BNDYGNodeStyleSetHeight(root, 102);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetHeight(root_child0, 10);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetHeight(root_child1, 10);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetHeight(root_child2, 10);
  BNDYGNodeInsertChild(root, root_child2, 2);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child2));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child2));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, justify_content_column_flex_end) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetJustifyContent(root, BNDYGJustifyFlexEnd);
  BNDYGNodeStyleSetWidth(root, 102);
  BNDYGNodeStyleSetHeight(root, 102);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetHeight(root_child0, 10);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetHeight(root_child1, 10);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetHeight(root_child2, 10);
  BNDYGNodeInsertChild(root, root_child2, 2);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(72, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(82, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(92, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child2));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(72, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(82, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(92, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child2));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, justify_content_column_center) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetJustifyContent(root, BNDYGJustifyCenter);
  BNDYGNodeStyleSetWidth(root, 102);
  BNDYGNodeStyleSetHeight(root, 102);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetHeight(root_child0, 10);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetHeight(root_child1, 10);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetHeight(root_child2, 10);
  BNDYGNodeInsertChild(root, root_child2, 2);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(36, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(46, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(56, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child2));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(36, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(46, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(56, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child2));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, justify_content_column_space_between) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetJustifyContent(root, BNDYGJustifySpaceBetween);
  BNDYGNodeStyleSetWidth(root, 102);
  BNDYGNodeStyleSetHeight(root, 102);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetHeight(root_child0, 10);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetHeight(root_child1, 10);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetHeight(root_child2, 10);
  BNDYGNodeInsertChild(root, root_child2, 2);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(46, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(92, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child2));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(46, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(92, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child2));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, justify_content_column_space_around) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetJustifyContent(root, BNDYGJustifySpaceAround);
  BNDYGNodeStyleSetWidth(root, 102);
  BNDYGNodeStyleSetHeight(root, 102);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetHeight(root_child0, 10);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetHeight(root_child1, 10);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetHeight(root_child2, 10);
  BNDYGNodeInsertChild(root, root_child2, 2);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(12, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(46, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child2));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(12, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(46, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child2));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, justify_content_row_min_width_and_margin) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetJustifyContent(root, BNDYGJustifyCenter);
  BNDYGNodeStyleSetMargin(root, BNDYGEdgeLeft, 100);
  BNDYGNodeStyleSetMinWidth(root, 50);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 20);
  BNDYGNodeStyleSetHeight(root_child0, 20);
  BNDYGNodeInsertChild(root, root_child0, 0);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(15, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child0));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(15, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child0));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, justify_content_row_max_width_and_margin) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetJustifyContent(root, BNDYGJustifyCenter);
  BNDYGNodeStyleSetMargin(root, BNDYGEdgeLeft, 100);
  BNDYGNodeStyleSetWidth(root, 100);
  BNDYGNodeStyleSetMaxWidth(root, 80);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 20);
  BNDYGNodeStyleSetHeight(root_child0, 20);
  BNDYGNodeInsertChild(root, root_child0, 0);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child0));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child0));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, justify_content_column_min_height_and_margin) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetJustifyContent(root, BNDYGJustifyCenter);
  BNDYGNodeStyleSetMargin(root, BNDYGEdgeTop, 100);
  BNDYGNodeStyleSetMinHeight(root, 50);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 20);
  BNDYGNodeStyleSetHeight(root_child0, 20);
  BNDYGNodeInsertChild(root, root_child0, 0);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(15, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child0));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(50, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(15, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child0));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, justify_content_colunn_max_height_and_margin) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetJustifyContent(root, BNDYGJustifyCenter);
  BNDYGNodeStyleSetMargin(root, BNDYGEdgeTop, 100);
  BNDYGNodeStyleSetHeight(root, 100);
  BNDYGNodeStyleSetMaxHeight(root, 80);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetWidth(root_child0, 20);
  BNDYGNodeStyleSetHeight(root_child0, 20);
  BNDYGNodeInsertChild(root, root_child0, 0);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child0));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(100, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(80, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(30, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, BNDYGNodeLayoutGetHeight(root_child0));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, justify_content_column_space_evenly) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetJustifyContent(root, BNDYGJustifySpaceEvenly);
  BNDYGNodeStyleSetWidth(root, 102);
  BNDYGNodeStyleSetHeight(root, 102);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetHeight(root_child0, 10);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetHeight(root_child1, 10);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetHeight(root_child2, 10);
  BNDYGNodeInsertChild(root, root_child2, 2);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(18, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(46, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(74, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child2));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(18, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(46, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(74, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child2));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}

TEST(YogaTest, justify_content_row_space_evenly) {
  const BNDYGConfigRef config = BNDYGConfigNew();

  const BNDYGNodeRef root = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetFlexDirection(root, BNDYGFlexDirectionRow);
  BNDYGNodeStyleSetJustifyContent(root, BNDYGJustifySpaceEvenly);
  BNDYGNodeStyleSetWidth(root, 102);
  BNDYGNodeStyleSetHeight(root, 102);

  const BNDYGNodeRef root_child0 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetHeight(root_child0, 10);
  BNDYGNodeInsertChild(root, root_child0, 0);

  const BNDYGNodeRef root_child1 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetHeight(root_child1, 10);
  BNDYGNodeInsertChild(root, root_child1, 1);

  const BNDYGNodeRef root_child2 = BNDYGNodeNewWithConfig(config);
  BNDYGNodeStyleSetHeight(root_child2, 10);
  BNDYGNodeInsertChild(root, root_child2, 2);
  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionLTR);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(26, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(51, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(77, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child2));

  BNDYGNodeCalculateLayout(root, BNDYGUndefined, BNDYGUndefined, BNDYGDirectionRTL);

  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, BNDYGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(77, BNDYGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(51, BNDYGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(26, BNDYGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(0, BNDYGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, BNDYGNodeLayoutGetHeight(root_child2));

  BNDYGNodeFreeRecursive(root);

  BNDYGConfigFree(config);
}
